### ISSUE TITLE
setting raylib flags

### ISSUE THREAD

**Issue by cosmopolitics** [tjammer/raylib-ocaml#43]
I am quite new to ocaml and its build system but how does one set options like linux-display-backend to wayland

**Comment by tjammer** [comment]
There is no general way to achieve this with opam, but with raylib, it's quite straight-forward.
These flags are configured at build time and require passing some flags to the Makefile. Fortunately, we don't have to touch the Makefile (or dune build file) since environment variables are also picked up.

In short, it's enough to configure this when installing raylib through opam. In the install step raylib will be built and the flag will be picked up.

``` sh
USE_WAYLAND_DISPLAY=TRUE opam install raylib
```

If you have raylib installed already, you might need to uninstall it first, or force a rebuild `opam reinstall`.

Note that for the wayland build you need additional dependencies, for details see https://github.com/raysan5/raylib/wiki/Working-on-GNU-Linux#wayland
